server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    #表示是否将自己注册到eureka server，默认为true。由于当前服务就是eureka server,所以false
    registerWithEureka: false
    #是否从eureka server获取注册信息，默认为true。
    fetchRegistry: false
    serviceUrl:
      #设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:8761/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756